---
author: SHUNYA KIMURA
title: PhD Researcher
format:
  classic-cv-pdf: default
# cvfooter:
#   left: "mr.schochastics.net"
#   right: "github.com/schochastics"
cvcolor: 58748F #without `#`
# cvfont: raleway #texlive fonts like raleway,fetamont,gillius,comfortaa
cvmeta:
  - title: Status
    left: PhD Researcher at the Geospatial Analytics and Computing Group, University College London
    right: London, UK
  - title: Field
    left: Data Mining, Machine Learning, Spatial Statistics
    right: "+447399980267"
  - title: Techs
    left: R, Python, Apache Hive, Google BigQuery, Git, Quarto
    right: kimushun618@gmail.com
execute:
  echo: false
---

```{r}
#| label: cvevents
cvevents <- function(tbl, when, what, where, details) {

    command_start <- "\\cvevent"

    res <- paste0(
        command_start, "{", tbl[[when]], "}", 
        "{", tbl[[what]], "}",
        "{", tbl[[where]], "}")
    
    tbl[[details]] <- sapply(tbl[[details]], function(x) paste0("{", x, "}", collapse = ","))
    res <- paste0(res, "{",tbl[[details]],"}")

    cat(res, sep = "\n")
}
```

# EDUCATION

```{r}
#| label: education
#| output: asis
tibble::tribble(
    ~degree, ~uni, ~loc, ~dates, ~details,
    "MPhil/PhD Human Geography", "University College London", "London, UK", "Sep. 2021 - Present"
    , c("\\textbf{Project:} \\textit{Typologies of Online Gambling Behaviour in Great Britain: Insights from Geographic Smart Data Analysis}; supervised by Professor Paul Longley and Dr Justin Van Dijk.",
        "\\textbf{Funding:} Bloomsbury and East London Doctoral Training Partnership (UBEL DTP) - Economic and Social Research Council (ESRC) Studentship; co-funded by GambleAware.",
        "\\textbf{Data Mining:} In collaboration with our industry partner, I work with consumer datasets distributed across their data warehouse system. External data linkages are conducted while adhering to appropriate procedures for information governance. [Technologies: Apache Hive, Google Bigquery, R, GitLab, etc.]",
        "\\textbf{Feature Engineering:} Designed novel behavioural markers to facilitate cross-customer comparisons, providing enhanced analytical insights into how users engage with the platform. [Libraries: arrow, datatable, tidyr, lubridate, sf, ggplot2, etc.]",
        "\\textbf{Unsupervised Machine Learning:} Segmented customers into 11 distinct groups based on their revealed behaviour by applying dimensionality reduction techniques combined with clustering algorithms. [Libraries: arrow, datatable, tidyr, stats, factoextra, motifcluster, sf, ggplot2, etc.]"
        ),

    "BA Geography with Quantitative Methods (1st Class)", "University College London", "London, UK", "Sep. 2018 - Aug. 2021"
    , c("\\textbf{Relevant Modules:} Introduction to Quantitative Research Methods (73\\%), Geocomputation (68.5\\%), Data Analysis (74.5\\%), Mining Social and Geographic Datasets with Python (80.9\\%)", 
        "\\textbf{Independent Work:} Dissertation (74\\%) utilised mobility data to conduct an empirial investigation into the usage of the JUMP (now LIME) e-bike share system in London. Several spatial and statistical analyses were conducted, including DBSCAN, KDE clustering and multilevel negative binomial regression. This work was nominated for the 2021 Transport Geography Research Group Undergraduate Dissertation Prize.", 
        "\\textbf{Advanced Data Analysis:} Garnered experience with analysing randomised experiments, observational causal inference methods, quasi-experimental methods and with panel data methods.")
) |>
    cvevents(when = "dates", what = "degree", where = "uni", details = "details")
```

# CONFERENCES AND TALKS

```{r}
#| label: talks
#| output: asis
tibble::tribble(
    ~talk, ~format, ~loc, ~dates, ~details,
    "Bristol Hub for Gambling Harms Research Joint Hybrid Seminar", "Oral presentation", "Bristol, UK", "Mar. 2024"
    , c("\\textit{Unveiling Online Gambling Behaviour: A Descriptive Analysis of Consumer Data}. The recording and slides are available on \\href{https://github.com/shunyakmr/AC/tree/main/BRISTOL_SEMINAR_2024}{the github link}."),

    "GIS Research UK (GISRUK) Glasgow", "Oral presentation", "Glasgow, UK", "Apr. 2023"
    , c("The slides are available on \\href{https://github.com/shunyakmr/AC/tree/main/GISRUK_2023}{the github link}.", "Kimura, S., Van Dijk, J.T., and Longley, P.A. \\textit{The Use of Consumer Data to Explore Geographic and Social Variations in Online Gambling}. Proceedings of the 31st Conference of GIS Research UK (GISRUK). Glasgow: University of Glasgow. doi: 10.5281/zenodo.7828456."),

    "GIS Research UK (GISRUK) Glasgow", "Co-author", "Glasgow, UK", "Apr. 2023"
    , c("Winner of the Best Paper Award", "Todd, J., Kimura S., O'Brien, O., and Cheshire, J. \\textit{Dominant Trip Purposes within a Dockless Bicycle Sharing System in London}. Proceedings of the 31st Conference of GIS Research UK (GISRUK), Glasgow: University of Glasgow. doi: 10.5281/zenodo.7828473."),

   #  "GambleAware Annual Conference 2022", "Poster presentation", "London, UK", "Dec. 2022",
   #  c(""),
   #
   "CDRC Data Partner Forum 2022 Oxford Saïd Business School", "Oral presentation", "Oxford, UK", "Nov. 2022",
   c("\\textit{A Classification of Online Gambling Behaviour in Great Britain}. The slides are available on \\href{https://github.com/shunyakmr/AC/tree/main/CDRC_FORUM_2022}{the github link}."),

    "GIS Research UK (GISRUK) Liverpool", "Oral presentation", "Liverpool, UK", "Apr. 2022"
   , c("Winner of the CASA Prize for Best Paper in Spatial Analysis. The slides are available on \\href{https://github.com/shunyakmr/AC/tree/main/GISRUK_2022}{the github link}.", "Kimura, S., Longley, P. A., and Van Dijk, J.T. \\textit{Exploring the spatial disparities in gambling risk and vulnerability}. Proceedings of the 30th Conference of GIS Research UK (GISRUK). Liverpool: University of Liverpool. doi: 10.5281/zenodo.6407146.")
) |>
    cvevents(when = "dates", what = "talk", where = "format", details = "details")
```

# GRANTS

```{r}
#| label: grants
#| output: asis
tibble::tribble(
    ~grant, ~amount, ~loc, ~dates, ~details,
    "UBEL DTP International Institutional Visit Scheme", "GBP 1,200", "Kyoto, Japan", "Sep. 2021 - Present"
    , c("A travel grant for a 35-day visiting research period at the Institute of Disaster Mitigation for Urban Cultural Heritage, Ritsumeikan University at Kyoto, Japan. Invited by Professor Keiji Yano.")
) |>
    cvevents(when = "dates", what = "grant", where = "amount", details = "details")
```

# RECENT EXPERIENCES

```{r}
#| label: experience
#| output: asis
tibble::tribble(
    ~role, ~org, ~loc, ~dates, ~details,
    "Senior Postgraduate Teaching Assistant", "University College London", "London, UK", "Jan. 2022 - Apr. 2023"
    , c("\\textbf{Teaching:} Led seminars and held academic support and feedback hours for the following modules: (1) Geography in the Field I and (2) II; (3) Geocomputation; (4) Introduction to Quantitative Research Methods; and (5) Data Analysis"),

    "Postgraduate Teaching Assistant", "Queen Mary University London", "London, UK", "Nov. 2022 - Jan. 2023"
    , c("\\textbf{Teaching:} Led seminars for the following module: Introduction to Research Methods"),

    "Data Analyst Intern", "BBC", "London, UK", "Aug. 2021 - Sep. 2021"
    , c("Generated actionable business insights by utilising R and Python to conduct analysis on unstructured data sourced from web scraping and social media pages.",
        "Rapidly acquired and implemented new skills within a tight deadline.",
        "Presented findings to various teams, providing key benchmarks for assessing the success of BBC’s social media platforms."),

   "Data Analyst Intern", "Climate Policy Initiative", "London, UK", "Jun. 2020 - Jul. 2020"
   ,c("Assisted in the creation of \\href{https://www.climatepolicyinitiative.org/netzerofinancetracker/methodology.pdf}{The Net Zero Finance Tracker} through data gathering and dashboard design. This tool provides a comprehensive assessment of the alignment between public and private finance and the Paris Agreement goals.",
      "Quickly adapted and learned new concepts in climate finance, showing flexibility in an unfamiliar domain.")
) |>
    cvevents(when = "dates", what = "role", where = "org", details = "details")
```

# PROFESSIONAL DEVELOPMENT

```{r}
#| label: development
#| output: asis
tibble::tribble(
    ~event, ~host, ~loc, ~dates, ~details,
    "Introduction to Bayesian Inference and Modelling", "UCL Social Data Institute", "London, UK", "Jul. 2023"
    , c("Participated in a four-day intensive course on Bayesian inference. The course covered the fundamentals of Bayesian statistics using RStudio and Stan. Taught by Dr Anwar Musah.",
        "Acquired skills in performing spatial risk prediction and quantifying uncertainty levels using exceedance probabilities for aerial data, which are currently employed in my PhD project."),

    "Advanced Topics in Social \\& Geographic Data Sciences", "UCL Geography", "London, UK", "Jan. 2022 - Mar. 2022"
    , c("Audited a module in the Social \\& Geographic Data Science MSc course. Led by Dr Stephen Law.",
        "Revised topics on statistical learning, including Deep Learning, Convolutional Neural Networks, and GeoAI.")
) |>
    cvevents(when = "dates", what = "event", where = "host", details = "details")
```

# LANGUAGE PROFICIENCY

\- **Japanese:** Native proficiency; **English:** Full professional proficiency; and **Arabic:** Beginner proficiency.
